export const timetableData = {
  NAME: "IwIK 2sem",
  SUBJECTS: {
    ELEKTRO: {
      name: "Elektrotechnika",
      teacher: "prof. A. Szromba / dr inż. K. Hawron / dr inż. B. Woszczyna",
      color: "bg-orange-600", // rgb(255, 69, 0)
    },
    VHDL: {
      name: "Programowanie w języku VHDL",
      teacher: "dr inż. M. Węgrzyn / dr inż. D. Dorota",
      color: "bg-red-500", // rgb(255, 99, 71)
    },
    EL_BAS: {
      name: "Podstawy elektroniki",
      teacher: "dr inż. A. Drwal / dr inż. S. Żaba",
      color: "bg-sky-700", // rgb(70, 130, 180)
    },
    MET_PROG: {
      name: "Metody programowania",
      teacher: "prof. Z. Kokosiński / mgr inż. G. Nowakowski",
      color: "bg-fuchsia-400", // rgb(218, 112, 214)
    },
    MET_OBL: {
      name: "Metody obliczeniowe",
      teacher:
        "dr inż. A. Romańska / mgr inż. K. Hatłas / mgr inż. J. Progorowicz",
      color: "bg-amber-800", // rgb(160, 82, 45)
    },
    ANG: {
      name: "Język angielski",
      teacher: "mgr A. Gunia-Tracz",
      color: "bg-pink-400", // rgb(255, 105, 180)
    },
    WF: {
      name: "Wychowanie fizyczne",
      teacher: "CSiR",
      color: "bg-green-500", // rgb(50, 205, 50)
    },
    NTS: {
      name: "Nauka, technika i społeczeństwo",
      teacher: "prof. K. Węc",
      color: "bg-teal-600", // rgb(95, 158, 160)
    },
    MAT_DYS: {
      name: "Matematyka dyskretna",
      teacher: "dr G. Gancarzewicz",
      color: "bg-blue-600", // rgb(65, 105, 225)
    },
  },
  SCHEDULE: [
    // -----------------------------------------------------
    // PONIEDZIAŁEK (day: 0)
    // -----------------------------------------------------
    {
      id: 401,
      subj: "ELEKTRO",
      type: "Wykład",
      groups: [],
      day: 0,
      start: "11:00",
      end: "12:30",
      room: "A3",
      weeks: "both",
    },
    {
      id: 402,
      subj: "VHDL",
      type: "Wykład",
      groups: [],
      day: 0,
      start: "12:45",
      end: "14:15",
      room: "A3",
      weeks: "both",
    },
    {
      id: 403,
      subj: "EL_BAS",
      type: "Wykład",
      groups: [],
      day: 0,
      start: "18:00",
      end: "19:30",
      room: "A3",
      weeks: "both",
    },

    // -----------------------------------------------------
    // WTOREK (day: 1)
    // -----------------------------------------------------
    // Blok 09:15
    {
      id: 404,
      subj: "ELEKTRO",
      type: "Laboratorium",
      groups: ["L7"],
      day: 1,
      start: "09:15",
      end: "10:45",
      room: "04",
      weeks: "both",
    },
    {
      id: 405,
      subj: "MET_PROG",
      type: "Laboratorium",
      groups: ["Lk2"],
      day: 1,
      start: "09:15",
      end: "10:45",
      room: "202",
      weeks: "both",
    },
    {
      id: 406,
      subj: "EL_BAS",
      type: "Laboratorium",
      groups: ["L6"],
      day: 1,
      start: "09:15",
      end: "10:45",
      room: "06",
      weeks: "both",
    },
    {
      id: 407,
      subj: "VHDL",
      type: "Laboratorium",
      groups: ["Lk3"],
      day: 1,
      start: "09:15",
      end: "10:45",
      room: "11",
      weeks: "both",
    },

    // Blok 11:00
    {
      id: 408,
      subj: "ELEKTRO",
      type: "Laboratorium",
      groups: ["L2"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "04",
      weeks: "both",
    },
    {
      id: 409,
      subj: "MET_PROG",
      type: "Laboratorium",
      groups: ["Lk3"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "202",
      weeks: "both",
    },
    {
      id: 410,
      subj: "EL_BAS",
      type: "Laboratorium",
      groups: ["L7"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "06",
      weeks: "both",
    },
    {
      id: 411,
      subj: "VHDL",
      type: "Laboratorium",
      groups: ["Lk4"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "11",
      weeks: "both",
    },

    // Blok 12:45
    {
      id: 412,
      subj: "ELEKTRO",
      type: "Laboratorium",
      groups: ["L4"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "04",
      weeks: "both",
    },
    {
      id: 413,
      subj: "ANG",
      type: "Lektorat",
      groups: ["Lek4"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "10",
      weeks: "both",
    },
    {
      id: 414,
      subj: "MET_OBL",
      type: "Laboratorium",
      groups: ["Lk2"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "12",
      weeks: "both",
    },

    // Blok 14:30
    {
      id: 415,
      subj: "ELEKTRO",
      type: "Laboratorium",
      groups: ["L1"],
      day: 1,
      start: "14:30",
      end: "16:00",
      room: "04",
      weeks: "odd",
    },
    {
      id: 416,
      subj: "ELEKTRO",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 1,
      start: "14:30",
      end: "16:00",
      room: "A1",
      weeks: "even",
    },
    {
      id: 417,
      subj: "MET_OBL",
      type: "Laboratorium",
      groups: ["Lk4"],
      day: 1,
      start: "14:30",
      end: "16:00",
      room: "13",
      weeks: "odd",
    },
    {
      id: 418,
      subj: "MET_PROG",
      type: "Laboratorium",
      groups: ["Lk5"],
      day: 1,
      start: "14:30",
      end: "16:00",
      room: "202",
      weeks: "odd",
    },
    {
      id: 419,
      subj: "EL_BAS",
      type: "Laboratorium",
      groups: ["L2"],
      day: 1,
      start: "14:30",
      end: "16:00",
      room: "06",
      weeks: "odd",
    },

    // Blok 16:15
    {
      id: 420,
      subj: "MET_OBL",
      type: "Laboratorium",
      groups: ["Lk5"],
      day: 1,
      start: "16:15",
      end: "17:45",
      room: "12",
      weeks: "even",
    },
    {
      id: 421,
      subj: "EL_BAS",
      type: "Laboratorium",
      groups: ["L3"],
      day: 1,
      start: "16:15",
      end: "17:45",
      room: "06",
      weeks: "even",
    },
    {
      id: 422,
      subj: "ELEKTRO",
      type: "Ćwiczenia",
      groups: ["Ć3"],
      day: 1,
      start: "16:15",
      end: "17:45",
      room: "A2",
      weeks: "even",
    },

    // Blok 18:00
    {
      id: 423,
      subj: "EL_BAS",
      type: "Laboratorium",
      groups: ["L4"],
      day: 1,
      start: "18:00",
      end: "19:30",
      room: "06",
      weeks: "even",
    },

    // -----------------------------------------------------
    // ŚRODA (day: 2)
    // -----------------------------------------------------
    {
      id: 424,
      subj: "WF",
      type: "Ćwiczenia",
      groups: ["C"],
      day: 2,
      start: "07:30",
      end: "10:30",
      room: "H/C",
      weeks: "both",
    },
    {
      id: 425,
      subj: "NTS",
      type: "Seminarium",
      groups: ["S1"],
      day: 2,
      start: "11:00",
      end: "12:30",
      room: "A4",
      weeks: "odd",
    },
    {
      id: 426,
      subj: "NTS",
      type: "Seminarium",
      groups: ["S2"],
      day: 2,
      start: "11:00",
      end: "12:30",
      room: "A4",
      weeks: "even",
    },
    {
      id: 427,
      subj: "MET_PROG",
      type: "Wykład",
      groups: [],
      day: 2,
      start: "12:45",
      end: "14:15",
      room: "A1",
      weeks: "both",
    },
    {
      id: 428,
      subj: "MET_OBL",
      type: "Wykład",
      groups: [],
      day: 2,
      start: "14:30",
      end: "16:00",
      room: "A1",
      weeks: "both",
    },

    // -----------------------------------------------------
    // CZWARTEK (day: 3)
    // -----------------------------------------------------
    // Blok 07:30
    {
      id: 429,
      subj: "MET_PROG",
      type: "Laboratorium",
      groups: ["Lk1"],
      day: 3,
      start: "07:30",
      end: "09:00",
      room: "202",
      weeks: "odd",
    },
    {
      id: 430,
      subj: "EL_BAS",
      type: "Laboratorium",
      groups: ["L5"],
      day: 3,
      start: "07:30",
      end: "09:00",
      room: "06",
      weeks: "odd",
    },
    {
      id: 431,
      subj: "VHDL",
      type: "Laboratorium",
      groups: ["Lk5"],
      day: 3,
      start: "07:30",
      end: "09:00",
      room: "11",
      weeks: "odd",
    },
    {
      id: 432,
      subj: "ANG",
      type: "Lektorat",
      groups: ["Lek3"],
      day: 3,
      start: "07:30",
      end: "09:00",
      room: "10",
      weeks: "even",
    },

    // Blok 09:15
    {
      id: 433,
      subj: "ELEKTRO",
      type: "Laboratorium",
      groups: ["L6"],
      day: 3,
      start: "09:15",
      end: "10:45",
      room: "04",
      weeks: "both",
    },
    {
      id: 434,
      subj: "ANG",
      type: "Lektorat",
      groups: ["Lek1"],
      day: 3,
      start: "09:15",
      end: "10:45",
      room: "10",
      weeks: "both",
    },
    {
      id: 435,
      subj: "MET_OBL",
      type: "Laboratorium",
      groups: ["Lk3"],
      day: 3,
      start: "09:15",
      end: "10:45",
      room: "12",
      weeks: "both",
    },

    // Blok 11:00
    {
      id: 436,
      subj: "ELEKTRO",
      type: "Laboratorium",
      groups: ["L5"],
      day: 3,
      start: "11:00",
      end: "12:30",
      room: "04",
      weeks: "both",
    },
    {
      id: 437,
      subj: "ANG",
      type: "Lektorat",
      groups: ["Lek2"],
      day: 3,
      start: "11:00",
      end: "12:30",
      room: "10",
      weeks: "both",
    },
    {
      id: 438,
      subj: "MET_OBL",
      type: "Laboratorium",
      groups: ["Lk1"],
      day: 3,
      start: "11:00",
      end: "12:30",
      room: "12",
      weeks: "both",
    },

    // Blok 12:45
    {
      id: 439,
      subj: "ELEKTRO",
      type: "Laboratorium",
      groups: ["L4"],
      day: 3,
      start: "12:45",
      end: "14:15",
      room: "04",
      weeks: "odd",
    },
    {
      id: 440,
      subj: "ELEKTRO",
      type: "Laboratorium",
      groups: ["L3"],
      day: 3,
      start: "12:45",
      end: "14:15",
      room: "04",
      weeks: "even",
    },
    {
      id: 441,
      subj: "ANG",
      type: "Lektorat",
      groups: ["Lek4"],
      day: 3,
      start: "12:45",
      end: "14:15",
      room: "10",
      weeks: "odd",
    },
    {
      id: 442,
      subj: "MET_OBL",
      type: "Laboratorium",
      groups: ["Lk2"],
      day: 3,
      start: "12:45",
      end: "14:15",
      room: "12",
      weeks: "odd",
    },
    {
      id: 443,
      subj: "MET_PROG",
      type: "Laboratorium",
      groups: ["Lk4"],
      day: 3,
      start: "12:45",
      end: "14:15",
      room: "202",
      weeks: "even",
    },
    {
      id: 444,
      subj: "EL_BAS",
      type: "Laboratorium",
      groups: ["L1"],
      day: 3,
      start: "12:45",
      end: "14:15",
      room: "06",
      weeks: "even",
    },

    // Blok 14:30
    {
      id: 445,
      subj: "ELEKTRO",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 3,
      start: "14:30",
      end: "16:00",
      room: "A1",
      weeks: "odd",
    },
    {
      id: 446,
      subj: "ELEKTRO",
      type: "Ćwiczenia",
      groups: ["Ć2"],
      day: 3,
      start: "14:30",
      end: "16:00",
      room: "A1",
      weeks: "even",
    },

    // Blok 16:15
    {
      id: 447,
      subj: "ELEKTRO",
      type: "Ćwiczenia",
      groups: ["Ć3"],
      day: 3,
      start: "16:15",
      end: "17:45",
      room: "A2",
      weeks: "odd",
    },

    // -----------------------------------------------------
    // PIĄTEK (day: 4)
    // -----------------------------------------------------
    {
      id: 448,
      subj: "MAT_DYS",
      type: "Wykład",
      groups: [],
      day: 4,
      start: "07:30",
      end: "09:00",
      room: "A1",
      weeks: "both",
    },

    // Tydzień nieparzysty (27.02)
    {
      id: 449,
      subj: "MAT_DYS",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 4,
      start: "09:15",
      end: "11:30",
      room: "A1",
      weeks: "odd",
    },
    {
      id: 450,
      subj: "MAT_DYS",
      type: "Ćwiczenia",
      groups: ["Ć2"],
      day: 4,
      start: "11:00",
      end: "12:30",
      room: "A1",
      weeks: "odd",
    },
    {
      id: 451,
      subj: "VHDL",
      type: "Laboratorium",
      groups: ["Lk1"],
      day: 4,
      start: "11:00",
      end: "12:30",
      room: "208G",
      weeks: "odd",
    },
    {
      id: 452,
      subj: "MAT_DYS",
      type: "Ćwiczenia",
      groups: ["Ć3"],
      day: 4,
      start: "12:45",
      end: "14:15",
      room: "A1",
      weeks: "odd",
    },
    {
      id: 453,
      subj: "VHDL",
      type: "Laboratorium",
      groups: ["Lk2"],
      day: 4,
      start: "12:45",
      end: "14:15",
      room: "208G",
      weeks: "odd",
    },

    // Tydzień parzysty (06.03) - przesunięcia godzinowe
    {
      id: 454,
      subj: "MAT_DYS",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 4,
      start: "09:15",
      end: "11:30",
      room: "A1",
      weeks: "even",
    }, // To samo co odd
    {
      id: 455,
      subj: "MAT_DYS",
      type: "Ćwiczenia",
      groups: ["Ć2"],
      day: 4,
      start: "11:45",
      end: "14:00",
      room: "A1",
      weeks: "even",
    },
    {
      id: 456,
      subj: "VHDL",
      type: "Laboratorium",
      groups: ["Lk1"],
      day: 4,
      start: "11:45",
      end: "14:00",
      room: "208G",
      weeks: "even",
    },
    {
      id: 457,
      subj: "MAT_DYS",
      type: "Ćwiczenia",
      groups: ["Ć3"],
      day: 4,
      start: "14:15",
      end: "16:30",
      room: "A1",
      weeks: "even",
    },
    {
      id: 458,
      subj: "VHDL",
      type: "Laboratorium",
      groups: ["Lk2"],
      day: 4,
      start: "14:15",
      end: "16:30",
      room: "208G",
      weeks: "even",
    },
    {
      id: 459,
      subj: "MAT_DYS",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 4,
      start: "14:30",
      end: "16:00",
      room: "A1",
      weeks: "even",
    }, // Dodatkowa grupa Ć1 w parzysty?
  ],
};
