export const timetableData = {
  NAME: "EiA 2sem",
  GROUPS: [
    { type: "C", prefix: "Ć", label: "Ćwiczenia" },
    { type: "L", prefix: "L", label: "Laboratoria" },
    { type: "Lek", prefix: "Lek", label: "Lektorat" },
    { type: "Lk", prefix: "Lk", label: "Lab. komp." },
    { type: "P", prefix: "P", label: "Projekt" },
  ],
  SUBJECTS: {
    ANAL: {
      name: "Analiza matematyczna",
      teacher: "dr A. Pudełko / mgr M. Ból / dr J. Czajkowski",
      color: "bg-indigo-900",
    },
    ANG01: {
      name: "Język angielski",
      teacher: "mgr J. Firganek / mgr A. Zwierzyńska-Dubis",
      color: "bg-sky-500",
    },
    NIEM01: {
      name: "Język niemiecki",
      teacher: "mgr E. Targosz",
      color: "bg-purple-800",
    },
    FRAN01: {
      name: "Język francuski",
      teacher: "mgr B. Heil",
      color: "bg-emerald-700",
    },
    PROG_CPP: {
      name: "Programowanie w C++",
      teacher:
        "dr inż. K. Suchenia / mgr inż. M. Raźny / dr inż. D. Gutenko / mgr inż. K. Kopera",
      color: "bg-purple-600",
    },
    ELEC_BAS: {
      name: "Podstawy elektroniki",
      teacher: "prof. A. Szromba / dr inż. A. Drwal / dr inż. S. Żaba",
      color: "bg-pink-600",
    },
    NUMER: {
      name: "Metody numeryczne",
      teacher: "dr inż. G. Pędrak / dr inż. M. Orkisz",
      color: "bg-green-600",
    },
    AUTOCAD: {
      name: "Geometria i grafika inżynierska w AUTOCAD",
      teacher: "prof. P. Małka / mgr inż. M. Gibas",
      color: "bg-pink-500",
    },
    FIZ01: {
      name: "Fizyka",
      teacher: "Pracownicy katedry",
      color: "bg-red-800",
    },
  },
  SCHEDULE: [
    // -----------------------------------------------------
    // PONIEDZIAŁEK (day: 0)
    // -----------------------------------------------------
    {
      id: 101,
      subj: "ANAL",
      type: "Wykład",
      teacher: "dr A. Pudełko",
      groups: [],
      day: 0,
      start: "07:30",
      end: "09:45",
      room: "A2",
      weeks: "both",
    },
    {
      id: 102,
      subj: "ANAL",
      type: "Ćwiczenia",
      teacher: "dr A. Pudełko",
      groups: ["Ć2"],
      day: 0,
      start: "10:00",
      end: "11:30",
      room: "A2",
      weeks: "both",
    },
    {
      id: 103,
      subj: "ANG01",
      type: "Lektorat",
      teacher: "mgr A. Zwierzyńska-Dubis",
      groups: ["Lek1"],
      day: 0,
      start: "10:00",
      end: "11:30",
      room: "139SJO",
      weeks: "both",
    },
    {
      id: 104,
      subj: "ANG01",
      type: "Lektorat",
      teacher: "mgr J. Firganek",
      groups: ["Lek5"],
      day: 0,
      start: "10:00",
      end: "11:30",
      room: "136SJO",
      weeks: "both",
    },
    {
      id: 105,
      subj: "ANAL",
      type: "Ćwiczenia",
      teacher: "mgr M. Ból",
      groups: ["Ć1"],
      day: 0,
      start: "11:45",
      end: "13:15",
      room: "A2",
      weeks: "both",
    },
    {
      id: 106,
      subj: "ANG01",
      type: "Lektorat",
      teacher: "mgr J. Firganek",
      groups: ["Lek3"],
      day: 0,
      start: "11:45",
      end: "13:15",
      room: "136SJO",
      weeks: "both",
    },
    {
      id: 107,
      subj: "NIEM01",
      type: "Lektorat",
      teacher: "mgr E. Targosz",
      groups: ["Lek"],
      day: 0,
      start: "11:45",
      end: "13:15",
      room: "139SJO",
      weeks: "both",
    },
    {
      id: 108,
      subj: "ANAL",
      type: "Ćwiczenia",
      teacher: "dr J. Czajkowski",
      groups: ["Ć3"],
      day: 0,
      start: "13:30",
      end: "15:00",
      room: "A2",
      weeks: "both",
    },
    {
      id: 109,
      subj: "ANG01",
      type: "Lektorat",
      teacher: "mgr J. Firganek",
      groups: ["Lek2"],
      day: 0,
      start: "13:30",
      end: "15:00",
      room: "136SJO",
      weeks: "both",
    },
    {
      id: 110,
      subj: "PROG_CPP",
      type: "Projekt",
      teacher: "mgr inż. M. Raźny",
      groups: ["P1"],
      day: 0,
      start: "13:30",
      end: "15:00",
      room: "19",
      weeks: "odd",
    },
    {
      id: 111,
      subj: "PROG_CPP",
      type: "Projekt",
      teacher: "mgr inż. M. Raźny",
      groups: ["P4"],
      day: 0,
      start: "13:30",
      end: "15:00",
      room: "19",
      weeks: "even",
    },
    {
      id: 112,
      subj: "ANAL",
      type: "Ćwiczenia",
      teacher: "dr J. Czajkowski",
      groups: ["Ć4"],
      day: 0,
      start: "15:15",
      end: "16:45",
      room: "A2",
      weeks: "both",
    },
    {
      id: 113,
      subj: "PROG_CPP",
      type: "Projekt",
      teacher: "mgr inż. M. Raźny",
      groups: ["P3"],
      day: 0,
      start: "15:15",
      end: "16:45",
      room: "19",
      weeks: "odd",
    },
    {
      id: 114,
      subj: "PROG_CPP",
      type: "Projekt",
      teacher: "mgr inż. M. Raźny",
      groups: ["P2"],
      day: 0,
      start: "15:15",
      end: "16:45",
      room: "19",
      weeks: "even",
    },
    {
      id: 115,
      subj: "PROG_CPP",
      type: "Projekt",
      teacher: "mgr inż. M. Raźny",
      groups: ["P5"],
      day: 0,
      start: "17:00",
      end: "18:30",
      room: "19",
      weeks: "odd",
    },
    {
      id: 116,
      subj: "AUTOCAD",
      type: "Projekt",
      teacher: "mgr inż. M. Gibas",
      groups: ["P5"],
      day: 0,
      start: "18:45",
      end: "20:15",
      room: "12",
      weeks: "odd",
    },

    // -----------------------------------------------------
    // WTOREK (day: 1)
    // -----------------------------------------------------
    {
      id: 117,
      subj: "AUTOCAD",
      type: "Projekt",
      teacher: "mgr inż. M. Gibas",
      groups: ["P2"],
      day: 1,
      start: "07:30",
      end: "09:00",
      room: "12",
      weeks: "odd",
    },
    {
      id: 118,
      subj: "AUTOCAD",
      type: "Projekt",
      teacher: "mgr inż. M. Gibas",
      groups: ["P1"],
      day: 1,
      start: "07:30",
      end: "09:00",
      room: "12",
      weeks: "even",
    },
    {
      id: 119,
      subj: "ELEC_BAS",
      type: "Wykład",
      teacher: "prof. A. Szromba",
      groups: [],
      day: 1,
      start: "09:15",
      end: "10:45",
      room: "A4",
      weeks: "both",
    },
    {
      id: 120,
      subj: "ANG01",
      type: "Lektorat",
      teacher: "mgr A. Zwierzyńska-Dubis",
      groups: ["Lek4"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "150SJO",
      weeks: "both",
    },
    {
      id: 121,
      subj: "ELEC_BAS",
      type: "Ćwiczenia",
      teacher: "prof. A. Szromba",
      groups: ["Ć2"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "A4",
      weeks: "odd",
    },
    {
      id: 122,
      subj: "ELEC_BAS",
      type: "Ćwiczenia",
      teacher: "prof. A. Szromba",
      groups: ["Ć1"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "A4",
      weeks: "even",
    },
    {
      id: 123,
      subj: "NUMER",
      type: "Wykład",
      teacher: "dr inż. G. Pędrak",
      groups: [],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "A3",
      weeks: "odd",
    },
    {
      id: 124,
      subj: "PROG_CPP",
      type: "Projekt",
      teacher: "dr inż. D. Gutenko",
      groups: ["P6"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "101B",
      weeks: "even",
    },
    {
      id: 125,
      subj: "AUTOCAD",
      type: "Wykład",
      teacher: "prof. P. Małka",
      groups: [],
      day: 1,
      start: "14:30",
      end: "16:00",
      room: "A4",
      weeks: "odd",
    },
    {
      id: 126,
      subj: "PROG_CPP",
      type: "Projekt",
      teacher: "dr inż. D. Gutenko",
      groups: ["P7"],
      day: 1,
      start: "14:30",
      end: "16:00",
      room: "101B",
      weeks: "even",
    },
    {
      id: 127,
      subj: "AUTOCAD",
      type: "Laboratorium komputerowe",
      teacher: "prof. P. Małka",
      groups: ["Lk6"],
      day: 1,
      start: "16:15",
      end: "17:45",
      room: "13",
      weeks: "both",
    },
    {
      id: 128,
      subj: "PROG_CPP",
      type: "Laboratorium komputerowe",
      teacher: "dr inż. D. Gutenko",
      groups: ["Lk7"],
      day: 1,
      start: "16:15",
      end: "17:45",
      room: "19",
      weeks: "both",
    },
    {
      id: 129,
      subj: "AUTOCAD",
      type: "Laboratorium komputerowe",
      teacher: "prof. P. Małka",
      groups: ["Lk7"],
      day: 1,
      start: "18:00",
      end: "19:30",
      room: "13",
      weeks: "both",
    },
    {
      id: 130,
      subj: "PROG_CPP",
      type: "Laboratorium komputerowe",
      teacher: "dr inż. D. Gutenko",
      groups: ["Lk6"],
      day: 1,
      start: "18:00",
      end: "19:30",
      room: "19",
      weeks: "both",
    },
    {
      id: 131,
      subj: "AUTOCAD",
      type: "Projekt",
      teacher: "prof. P. Małka",
      groups: ["P6"],
      day: 1,
      start: "19:45",
      end: "21:15",
      room: "13",
      weeks: "odd",
    },
    {
      id: 132,
      subj: "AUTOCAD",
      type: "Projekt",
      teacher: "prof. P. Małka",
      groups: ["P7"],
      day: 1,
      start: "19:45",
      end: "21:15",
      room: "13",
      weeks: "even",
    },

    // -----------------------------------------------------
    // ŚRODA (day: 2)
    // -----------------------------------------------------
    {
      id: 133,
      subj: "NUMER",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. G. P?drak",
      groups: ["Lk1"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "202",
      weeks: "odd",
    },
    {
      id: 134,
      subj: "NUMER",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. G. P?drak",
      groups: ["Lk2"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "202",
      weeks: "even",
    },
    {
      id: 135,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "mgr in?. M. Ra?ny",
      groups: ["L5"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "06",
      weeks: "both",
    },
    {
      id: 136,
      subj: "NUMER",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. M. Orkisz",
      groups: ["Lk3"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "202",
      weeks: "odd",
    },
    {
      id: 137,
      subj: "NUMER",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. M. Orkisz",
      groups: ["Lk5"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "202",
      weeks: "even",
    },
    {
      id: 138,
      subj: "ELEC_BAS",
      type: "Ćwiczenia",
      teacher: "prof. A. Szromba",
      groups: ["Ć3"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "9",
      weeks: "odd",
    },
    {
      id: 139,
      subj: "ELEC_BAS",
      type: "Ćwiczenia",
      teacher: "prof. A. Szromba",
      groups: ["Ć4"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "9",
      weeks: "even",
    },
    {
      id: 140,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "mgr in?. M. Ra?ny",
      groups: ["L6"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "06",
      weeks: "both",
    },
    {
      id: 141,
      subj: "PROG_CPP",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. D. Gutenko",
      groups: ["Lk1"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "19",
      weeks: "both",
    },
    {
      id: 142,
      subj: "NUMER",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. M. Orkisz",
      groups: ["Lk4"],
      day: 2,
      start: "15:15",
      end: "16:45",
      room: "202",
      weeks: "odd",
    },
    {
      id: 143,
      subj: "NUMER",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. M. Orkisz",
      groups: ["Lk6"],
      day: 2,
      start: "15:15",
      end: "16:45",
      room: "202",
      weeks: "even",
    },
    {
      id: 144,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "mgr in?. M. Ra?ny",
      groups: ["L7"],
      day: 2,
      start: "15:15",
      end: "16:45",
      room: "06",
      weeks: "both",
    },
    {
      id: 145,
      subj: "PROG_CPP",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. D. Gutenko",
      groups: ["Lk2"],
      day: 2,
      start: "15:15",
      end: "16:45",
      room: "19",
      weeks: "both",
    },
    {
      id: 146,
      subj: "FRAN01",
      type: "Lektorat",
      teacher: "mgr B. Heil",
      groups: ["Lek"],
      day: 2,
      start: "16:15",
      end: "17:45",
      room: "139SJO",
      weeks: "both",
    },
    {
      id: 147,
      subj: "NUMER",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. M. Orkisz",
      groups: ["Lk7"],
      day: 2,
      start: "17:00",
      end: "18:30",
      room: "202",
      weeks: "odd",
    },
    {
      id: 148,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "mgr in?. M. Ra?ny",
      groups: ["L8"],
      day: 2,
      start: "17:00",
      end: "18:30",
      room: "06",
      weeks: "both",
    },
    {
      id: 149,
      subj: "PROG_CPP",
      type: "Laboratorium komputerowe",
      teacher: "dr in?. D. Gutenko",
      groups: ["Lk3"],
      day: 2,
      start: "17:00",
      end: "18:30",
      room: "19",
      weeks: "both",
    },
    {
      id: 150,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "mgr in?. M. Ra?ny",
      groups: ["L11"],
      day: 2,
      start: "18:45",
      end: "20:15",
      room: "06",
      weeks: "both",
    },

    // -----------------------------------------------------
    // CZWARTEK (day: 3)
    // -----------------------------------------------------
    {
      id: 151,
      subj: "PROG_CPP",
      type: "Wykład",
      teacher: "dr in?. K. Suchenia",
      groups: [],
      day: 3,
      start: "08:15",
      end: "09:45",
      room: "A3",
      weeks: "both",
    },
    {
      id: 152,
      subj: "AUTOCAD",
      type: "Laboratorium komputerowe",
      teacher: "mgr in?. M. Gibas",
      groups: ["Lk1"],
      day: 3,
      start: "10:00",
      end: "11:30",
      room: "13",
      weeks: "both",
    },
    {
      id: 153,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "dr in?. A. Drwal",
      groups: ["L10"],
      day: 3,
      start: "10:00",
      end: "11:30",
      room: "06",
      weeks: "both",
    },
    {
      id: 154,
      subj: "AUTOCAD",
      type: "Laboratorium komputerowe",
      teacher: "mgr in?. M. Gibas",
      groups: ["Lk2"],
      day: 3,
      start: "11:45",
      end: "13:15",
      room: "13",
      weeks: "both",
    },
    {
      id: 155,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "dr in?. A. Drwal",
      groups: ["L9"],
      day: 3,
      start: "11:45",
      end: "13:15",
      room: "06",
      weeks: "both",
    },
    {
      id: 156,
      subj: "AUTOCAD",
      type: "Laboratorium komputerowe",
      teacher: "mgr in?. M. Gibas",
      groups: ["Lk3"],
      day: 3,
      start: "13:30",
      end: "15:00",
      room: "13",
      weeks: "both",
    },
    {
      id: 157,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "dr in?. S. ?aba",
      groups: ["L1"],
      day: 3,
      start: "13:30",
      end: "15:00",
      room: "06",
      weeks: "both",
    },
    {
      id: 158,
      subj: "AUTOCAD",
      type: "Laboratorium komputerowe",
      teacher: "mgr in?. M. Gibas",
      groups: ["Lk4"],
      day: 3,
      start: "15:15",
      end: "16:45",
      room: "13",
      weeks: "both",
    },
    {
      id: 159,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "dr in?. S. ?aba",
      groups: ["L2"],
      day: 3,
      start: "15:15",
      end: "16:45",
      room: "06",
      weeks: "both",
    },
    {
      id: 160,
      subj: "AUTOCAD",
      type: "Laboratorium komputerowe",
      teacher: "mgr in?. M. Gibas",
      groups: ["Lk5"],
      day: 3,
      start: "17:00",
      end: "18:30",
      room: "13",
      weeks: "both",
    },
    {
      id: 161,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "dr in?. S. ?aba",
      groups: ["L4"],
      day: 3,
      start: "17:00",
      end: "18:30",
      room: "06",
      weeks: "both",
    },
    {
      id: 162,
      subj: "PROG_CPP",
      type: "Laboratorium komputerowe",
      teacher: "mgr in?. K. Kopera",
      groups: ["Lk4"],
      day: 3,
      start: "17:00",
      end: "18:30",
      room: "101B",
      weeks: "both",
    },
    {
      id: 163,
      subj: "AUTOCAD",
      type: "Projekt",
      teacher: "mgr in?. M. Gibas",
      groups: ["P3"],
      day: 3,
      start: "18:45",
      end: "20:15",
      room: "13",
      weeks: "odd",
    },
    {
      id: 164,
      subj: "AUTOCAD",
      type: "Projekt",
      teacher: "mgr in?. M. Gibas",
      groups: ["P4"],
      day: 3,
      start: "18:45",
      end: "20:15",
      room: "13",
      weeks: "even",
    },
    {
      id: 165,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      teacher: "dr in?. S. ?aba",
      groups: ["L3"],
      day: 3,
      start: "18:45",
      end: "20:15",
      room: "06",
      weeks: "both",
    },
    {
      id: 166,
      subj: "PROG_CPP",
      type: "Laboratorium komputerowe",
      teacher: "mgr in?. K. Kopera",
      groups: ["Lk5"],
      day: 3,
      start: "18:45",
      end: "20:15",
      room: "101B",
      weeks: "both",
    },

    // -----------------------------------------------------
    // PIĄTEK (day: 4)
    // -----------------------------------------------------
    {
      id: 167,
      subj: "FIZ01",
      type: "Ćwiczenia",
      teacher: "Fizyka",
      groups: ["Ć1"],
      day: 4,
      start: "09:15",
      end: "14:15",
      room: "F",
      weeks: "both",
    },
  ],
};
