export const timetableData = {
  NAME: "EiA 4sem",
  GROUPS: [
    { type: "C", prefix: "Ć", label: "Ćwiczenia" },
    { type: "L", prefix: "L", label: "Laboratoria" },
    { type: "Lk", prefix: "Lk", label: "Lab. komp." },
    { type: "Lek", prefix: "Lek", label: "Lektorat" },
    { type: "P", prefix: "P", label: "Projekt" },
  ],
  SUBJECTS: {
    MASZ: {
      name: "Maszyny elektryczne",
      teacher:
        "dr inż. J. Tulicki / dr inż. A. Shymanska / dr inż. M. Sierżęga",
      color: "bg-indigo-900",
    },
    LABVIEW: {
      name: "Podstawy programowania w LabVIEW",
      teacher: "dr inż. T. Makowski / mgr inż. K. Sołtys",
      color: "bg-blue-500",
    },
    SIECI: {
      name: "Sieci i urządzenia elektryczne",
      teacher: "dr inż. T. Sieńko / mgr inż. D. Mamcarz",
      color: "bg-sky-400",
    },
    MICRO: {
      name: "Technika mikroprocesorowa",
      teacher: "dr inż. K. Suchenia / mgr inż. M. Raźny / dr inż. A. Drwal",
      color: "bg-purple-800",
    },
    ENERGO: {
      name: "Energoelektronika",
      teacher: "prof. W. Mazgaj / dr inż. W. Czuchra / mgr inż. M. Wawro",
      color: "bg-pink-600",
    },
    ANG01: {
      name: "Język angielski",
      teacher: "mgr J. Firganek",
      color: "bg-pink-400",
    },
    WF: {
      name: "Wychowanie fizyczne",
      teacher: "CSiR",
      color: "bg-green-500",
    },
    UKLADY: {
      name: "Układy elektromechaniczne",
      teacher: "dr inż. Z. Pilch",
      color: "bg-green-800",
    },
    PSPICE: {
      name: "Podstawy programu Pspice",
      teacher: "dr inż. Z. Szular",
      color: "bg-red-900",
    },
  },
  SCHEDULE: [
    // PONIEDZIAŁEK
    {
      id: 301,
      subj: "SIECI",
      type: "Wykład",
      groups: [],
      day: 0,
      start: "07:30",
      end: "09:00",
      room: "A4",
      weeks: "both",
    },

    // Blok 9:15
    {
      id: 302,
      subj: "MASZ",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 0,
      start: "09:15",
      end: "10:45",
      room: "10",
      weeks: "odd",
    },
    {
      id: 303,
      subj: "MASZ",
      type: "Laboratorium",
      groups: ["L1", "L2"],
      day: 0,
      start: "09:15",
      end: "10:45",
      room: "01A/01B",
      weeks: "even",
    },
    {
      id: 304,
      subj: "LABVIEW",
      type: "Laboratorium komputerowe",
      groups: ["Lk5"],
      day: 0,
      start: "09:15",
      end: "10:45",
      room: "12",
      weeks: "odd",
    },
    {
      id: 305,
      subj: "LABVIEW",
      type: "Laboratorium komputerowe",
      groups: ["Lk6"],
      day: 0,
      start: "09:15",
      end: "10:45",
      room: "12",
      weeks: "even",
    },
    {
      id: 306,
      subj: "SIECI",
      type: "Laboratorium",
      groups: ["L4"],
      day: 0,
      start: "09:15",
      end: "10:45",
      room: "8",
      weeks: "odd",
    },
    {
      id: 307,
      subj: "SIECI",
      type: "Laboratorium",
      groups: ["L5"],
      day: 0,
      start: "09:15",
      end: "10:45",
      room: "8",
      weeks: "even",
    },
    {
      id: 308,
      subj: "MICRO",
      type: "Laboratorium",
      groups: ["L6"],
      day: 0,
      start: "09:15",
      end: "10:45",
      room: "208E",
      weeks: "both",
    },

    // Blok 11:00
    {
      id: 309,
      subj: "ENERGO",
      type: "Ćwiczenia",
      groups: ["Ć3"],
      day: 0,
      start: "11:00",
      end: "12:30",
      room: "A1",
      weeks: "both",
    },
    {
      id: 310,
      subj: "MASZ",
      type: "Ćwiczenia",
      groups: ["Ć2"],
      day: 0,
      start: "11:00",
      end: "12:30",
      room: "10",
      weeks: "both",
    },
    {
      id: 311,
      subj: "LABVIEW",
      type: "Laboratorium komputerowe",
      groups: ["Lk2"],
      day: 0,
      start: "11:00",
      end: "12:30",
      room: "12",
      weeks: "odd",
    },
    {
      id: 312,
      subj: "LABVIEW",
      type: "Laboratorium komputerowe",
      groups: ["Lk1"],
      day: 0,
      start: "11:00",
      end: "12:30",
      room: "12",
      weeks: "even",
    },
    {
      id: 313,
      subj: "SIECI",
      type: "Laboratorium",
      groups: ["L1"],
      day: 0,
      start: "11:00",
      end: "12:30",
      room: "8",
      weeks: "odd",
    },
    {
      id: 314,
      subj: "SIECI",
      type: "Laboratorium",
      groups: ["L3"],
      day: 0,
      start: "11:00",
      end: "12:30",
      room: "8",
      weeks: "even",
    },

    // Blok 12:45
    {
      id: 315,
      subj: "ENERGO",
      type: "Ćwiczenia",
      groups: ["Ć2"],
      day: 0,
      start: "12:45",
      end: "14:15",
      room: "A1",
      weeks: "both",
    },
    {
      id: 316,
      subj: "LABVIEW",
      type: "Laboratorium",
      groups: ["L1"],
      day: 0,
      start: "12:45",
      end: "14:15",
      room: "WA2",
      weeks: "odd",
    },
    {
      id: 317,
      subj: "LABVIEW",
      type: "Laboratorium",
      groups: ["L2"],
      day: 0,
      start: "12:45",
      end: "14:15",
      room: "WA2",
      weeks: "even",
    },
    {
      id: 318,
      subj: "MICRO",
      type: "Projekt",
      groups: ["L7", "P5"],
      day: 0,
      start: "12:45",
      end: "14:15",
      room: "06",
      weeks: "both",
    },

    // Blok 14:30
    {
      id: 319,
      subj: "LABVIEW",
      type: "Wykład",
      groups: [],
      day: 0,
      start: "14:30",
      end: "16:00",
      room: "A3",
      weeks: "odd",
    },
    {
      id: 320,
      subj: "LABVIEW",
      type: "Laboratorium",
      groups: ["L7"],
      day: 0,
      start: "14:30",
      end: "16:00",
      room: "WA2",
      weeks: "even",
    },
    {
      id: 321,
      subj: "ANG01",
      type: "Lektorat",
      groups: ["Lek2"],
      day: 0,
      start: "14:30",
      end: "16:00",
      room: "136SJO",
      weeks: "even",
    },
    {
      id: 322,
      subj: "MASZ",
      type: "Laboratorium",
      groups: ["L7", "L8"],
      day: 0,
      start: "14:30",
      end: "16:00",
      room: "01A/01B",
      weeks: "even",
    },
    {
      id: 323,
      subj: "MICRO",
      type: "Laboratorium",
      groups: ["L2"],
      day: 0,
      start: "14:30",
      end: "16:00",
      room: "208E",
      weeks: "even",
    },
    {
      id: 324,
      subj: "LABVIEW",
      type: "Laboratorium komputerowe",
      groups: ["Lk3"],
      day: 0,
      start: "14:30",
      end: "16:00",
      room: "12",
      weeks: "even",
    },

    // Blok 16:15
    {
      id: 325,
      subj: "LABVIEW",
      type: "Laboratorium",
      groups: ["L3"],
      day: 0,
      start: "16:15",
      end: "17:45",
      room: "WA2",
      weeks: "odd",
    },
    {
      id: 326,
      subj: "LABVIEW",
      type: "Laboratorium",
      groups: ["L4"],
      day: 0,
      start: "16:15",
      end: "17:45",
      room: "WA2",
      weeks: "even",
    },
    {
      id: 327,
      subj: "LABVIEW",
      type: "Laboratorium",
      groups: ["L8"],
      day: 0,
      start: "16:15",
      end: "17:45",
      room: "WA2",
      weeks: "even",
    },
    {
      id: 328,
      subj: "LABVIEW",
      type: "Laboratorium komputerowe",
      groups: ["Lk4"],
      day: 0,
      start: "16:15",
      end: "17:45",
      room: "12",
      weeks: "even",
    },
    {
      id: 329,
      subj: "MICRO",
      type: "Laboratorium",
      groups: ["L5"],
      day: 0,
      start: "16:15",
      end: "17:45",
      room: "208E",
      weeks: "even",
    },

    // Blok 18:00
    {
      id: 330,
      subj: "LABVIEW",
      type: "Laboratorium",
      groups: ["L5"],
      day: 0,
      start: "18:00",
      end: "19:30",
      room: "WA2",
      weeks: "odd",
    },
    {
      id: 331,
      subj: "LABVIEW",
      type: "Laboratorium",
      groups: ["L6"],
      day: 0,
      start: "18:00",
      end: "19:30",
      room: "L6",
      weeks: "even",
    },

    // Blok 19:45
    {
      id: 332,
      subj: "MICRO",
      type: "Laboratorium",
      groups: ["L8", "P6"],
      day: 0,
      start: "19:45",
      end: "21:15",
      room: "06",
      weeks: "both",
    },

    // WTOREK
    // Blok 11:00
    {
      id: 333,
      subj: "ANG01",
      type: "Lektorat",
      groups: ["Lek4"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "136SJO",
      weeks: "both",
    },
    {
      id: 334,
      subj: "MASZ",
      type: "Laboratorium",
      groups: ["L3", "L4"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "01A/01B",
      weeks: "both",
    },
    {
      id: 335,
      subj: "SIECI",
      type: "Laboratorium",
      groups: ["L2"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "8",
      weeks: "odd",
    },
    {
      id: 336,
      subj: "SIECI",
      type: "Laboratorium",
      groups: ["L6"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "8",
      weeks: "even",
    },
    {
      id: 337,
      subj: "MICRO",
      type: "Laboratorium",
      groups: ["L1"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "208E",
      weeks: "both",
    },

    // Blok 12:45
    {
      id: 338,
      subj: "ANG01",
      type: "Lektorat",
      groups: ["Lek1"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "136SJO",
      weeks: "both",
    },
    {
      id: 339,
      subj: "MASZ",
      type: "Laboratorium",
      groups: ["L5", "L6"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "01A/01B",
      weeks: "both",
    },
    {
      id: 340,
      subj: "SIECI",
      type: "Laboratorium",
      groups: ["L7"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "8",
      weeks: "odd",
    },
    {
      id: 341,
      subj: "SIECI",
      type: "Laboratorium",
      groups: ["L8"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "8",
      weeks: "even",
    },
    {
      id: 342,
      subj: "MICRO",
      type: "Laboratorium",
      groups: ["L4"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "208E",
      weeks: "both",
    },

    // ŚRODA
    {
      id: 343,
      subj: "WF",
      type: "Ćwiczenia",
      groups: ["C"],
      day: 2,
      start: "10:30",
      end: "12:30",
      room: "H/C",
      weeks: "both",
    },
    {
      id: 344,
      subj: "MICRO",
      type: "Wykład",
      groups: [],
      day: 2,
      start: "12:45",
      end: "14:15",
      room: "A4",
      weeks: "both",
    },
    {
      id: 345,
      subj: "MASZ",
      type: "Wykład",
      groups: [],
      day: 2,
      start: "14:30",
      end: "16:00",
      room: "A4",
      weeks: "both",
    },
    {
      id: 346,
      subj: "UKLADY",
      type: "Wykład",
      groups: [],
      day: 2,
      start: "16:15",
      end: "17:45",
      room: "A1",
      weeks: "both",
    },

    // Wieczorne laby/projekty układy
    {
      id: 347,
      subj: "UKLADY",
      type: "Laboratorium komputerowe",
      groups: ["Lk5"],
      day: 2,
      start: "18:00",
      end: "19:30",
      room: "12",
      weeks: "odd",
    },
    {
      id: 348,
      subj: "UKLADY",
      type: "Projekt",
      groups: ["P5"],
      day: 2,
      start: "18:00",
      end: "19:30",
      room: "12",
      weeks: "even",
    },
    {
      id: 349,
      subj: "UKLADY",
      type: "Laboratorium komputerowe",
      groups: ["Lk6"],
      day: 2,
      start: "19:45",
      end: "21:15",
      room: "12",
      weeks: "odd",
    },
    {
      id: 350,
      subj: "UKLADY",
      type: "Projekt",
      groups: ["P6"],
      day: 2,
      start: "19:45",
      end: "21:15",
      room: "12",
      weeks: "even",
    },

    // CZWARTEK
    {
      id: 351,
      subj: "PSPICE",
      type: "Wykład",
      groups: [],
      day: 3,
      start: "07:30",
      end: "09:00",
      room: "A4",
      weeks: "both",
    },

    // Blok 9:15+
    {
      id: 352,
      subj: "ENERGO",
      type: "Laboratorium",
      groups: ["L1"],
      day: 3,
      start: "09:15",
      end: "11:30",
      room: "013B",
      weeks: "odd",
    },
    {
      id: 353,
      subj: "ENERGO",
      type: "Laboratorium",
      groups: ["L3"],
      day: 3,
      start: "09:15",
      end: "11:30",
      room: "013B",
      weeks: "even",
    },
    {
      id: 354,
      subj: "ANG01",
      type: "Lektorat",
      groups: ["Lek3"],
      day: 3,
      start: "09:15",
      end: "10:45",
      room: "136SJO",
      weeks: "both",
    },
    {
      id: 355,
      subj: "MASZ",
      type: "Ćwiczenia",
      groups: ["Ć3"],
      day: 3,
      start: "09:15",
      end: "10:45",
      room: "A1",
      weeks: "both",
    },
    {
      id: 356,
      subj: "PSPICE",
      type: "Laboratorium komputerowe",
      groups: ["Lk1"],
      day: 3,
      start: "09:15",
      end: "10:45",
      room: "109B",
      weeks: "even",
    },
    {
      id: 357,
      subj: "PSPICE",
      type: "Laboratorium komputerowe",
      groups: ["Lk2"],
      day: 3,
      start: "09:15",
      end: "10:45",
      room: "109B",
      weeks: "odd",
    },

    // Blok 11:00+
    {
      id: 358,
      subj: "PSPICE",
      type: "Laboratorium komputerowe",
      groups: ["Lk3"],
      day: 3,
      start: "11:00",
      end: "12:30",
      room: "109B",
      weeks: "odd",
    },
    {
      id: 359,
      subj: "PSPICE",
      type: "Laboratorium komputerowe",
      groups: ["Lk6"],
      day: 3,
      start: "11:00",
      end: "12:30",
      room: "109B",
      weeks: "even",
    },

    // Blok 11:45+
    {
      id: 360,
      subj: "ENERGO",
      type: "Laboratorium",
      groups: ["L2"],
      day: 3,
      start: "11:45",
      end: "14:00",
      room: "013B",
      weeks: "odd",
    },
    {
      id: 361,
      subj: "ENERGO",
      type: "Laboratorium",
      groups: ["L6"],
      day: 3,
      start: "11:45",
      end: "14:00",
      room: "013B",
      weeks: "even",
    },

    // Blok 12:30
    {
      id: 362,
      subj: "UKLADY",
      type: "Ćwiczenia",
      groups: ["Ć3"],
      day: 3,
      start: "12:30",
      end: "14:00",
      room: "A1",
      weeks: "odd",
    },
    {
      id: 363,
      subj: "UKLADY",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 3,
      start: "12:30",
      end: "14:00",
      room: "A1",
      weeks: "even",
    },
    {
      id: 364,
      subj: "PSPICE",
      type: "Laboratorium komputerowe",
      groups: ["Lk4"],
      day: 3,
      start: "12:45",
      end: "14:15",
      room: "109B",
      weeks: "odd",
    },
    {
      id: 365,
      subj: "PSPICE",
      type: "Laboratorium komputerowe",
      groups: ["Lk5"],
      day: 3,
      start: "12:45",
      end: "14:15",
      room: "109B",
      weeks: "even",
    },

    // Blok 14:15+
    {
      id: 366,
      subj: "ENERGO",
      type: "Laboratorium",
      groups: ["L5"],
      day: 3,
      start: "14:15",
      end: "16:30",
      room: "013B",
      weeks: "odd",
    },
    {
      id: 367,
      subj: "ENERGO",
      type: "Laboratorium",
      groups: ["L7"],
      day: 3,
      start: "14:15",
      end: "16:30",
      room: "013B",
      weeks: "even",
    },
    {
      id: 368,
      subj: "UKLADY",
      type: "Laboratorium komputerowe",
      groups: ["Lk1"],
      day: 3,
      start: "14:15",
      end: "15:45",
      room: "12",
      weeks: "odd",
    },
    {
      id: 369,
      subj: "UKLADY",
      type: "Projekt",
      groups: ["P1"],
      day: 3,
      start: "14:15",
      end: "15:45",
      room: "12",
      weeks: "even",
    },

    // Blok 16:00+
    {
      id: 370,
      subj: "UKLADY",
      type: "Laboratorium komputerowe",
      groups: ["Lk2"],
      day: 3,
      start: "16:00",
      end: "17:30",
      room: "12",
      weeks: "odd",
    },
    {
      id: 371,
      subj: "UKLADY",
      type: "Projekt",
      groups: ["P3"],
      day: 3,
      start: "16:00",
      end: "17:30",
      room: "12",
      weeks: "even",
    },

    // Blok 16:45+
    {
      id: 372,
      subj: "ENERGO",
      type: "Laboratorium",
      groups: ["L4"],
      day: 3,
      start: "16:45",
      end: "19:00",
      room: "013B",
      weeks: "odd",
    },
    {
      id: 373,
      subj: "ENERGO",
      type: "Laboratorium",
      groups: ["L8"],
      day: 3,
      start: "16:45",
      end: "19:00",
      room: "013B",
      weeks: "even",
    },

    // Blok 17:45+
    {
      id: 374,
      subj: "UKLADY",
      type: "Laboratorium komputerowe",
      groups: ["Lk4"],
      day: 3,
      start: "17:45",
      end: "19:15",
      room: "12",
      weeks: "odd",
    },
    {
      id: 375,
      subj: "UKLADY",
      type: "Projekt",
      groups: ["P2"],
      day: 3,
      start: "17:45",
      end: "19:15",
      room: "12",
      weeks: "even",
    },

    // Blok 19:30+
    {
      id: 376,
      subj: "UKLADY",
      type: "Laboratorium komputerowe",
      groups: ["Lk3"],
      day: 3,
      start: "19:30",
      end: "21:00",
      room: "12",
      weeks: "odd",
    },
    {
      id: 377,
      subj: "UKLADY",
      type: "Projekt",
      groups: ["P4"],
      day: 3,
      start: "19:30",
      end: "21:00",
      room: "12",
      weeks: "even",
    },

    // PIĄTEK
    {
      id: 378,
      subj: "ENERGO",
      type: "Wykład",
      groups: [],
      day: 4,
      start: "10:00",
      end: "12:15",
      room: "A4",
      weeks: "both",
    },
    {
      id: 379,
      subj: "ENERGO",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 4,
      start: "12:30",
      end: "14:00",
      room: "A4",
      weeks: "both",
    },
    {
      id: 380,
      subj: "UKLADY",
      type: "Ćwiczenia",
      groups: ["Ć2"],
      day: 4,
      start: "12:30",
      end: "14:00",
      room: "10",
      weeks: "odd",
    },
  ],
};
