export const timetableData = {
  SUBJECTS: {
    ANAL: {
      name: "Analiza matematyczna",
      teacher: "dr A. Pudełko / mgr M. Ból / dr J. Czajkowski",
      color: "bg-indigo-900", // rgb(26, 35, 126)
    },
    ANG01: {
      name: "Język angielski",
      teacher: "mgr J. Firganek / mgr A. Zwierzyńska-Dubis",
      color: "bg-sky-500", // rgb(30, 144, 255)
    },
    PROG_CPP: {
      name: "Programowanie w C++",
      teacher:
        "dr inż. K. Suchenia / mgr inż. M. Raźny / dr inż. D. Gutenko / mgr inż. K. Kopera",
      color: "bg-sky-400", // rgb(0, 191, 255)
    },
    NIEM01: {
      name: "Język niemiecki",
      teacher: "mgr E. Targosz",
      color: "bg-purple-800", // rgb(128, 0, 128)
    },
    ELEC_BAS: {
      name: "Podstawy elektroniki",
      teacher: "prof. A. Szromba / dr inż. A. Drwal / dr inż. S. Żaba",
      color: "bg-pink-700", // rgb(199, 21, 133)
    },
    NUMER: {
      name: "Metody numeryczne",
      teacher: "dr inż. G. Pędrak / dr inż. M. Orkisz",
      color: "bg-green-500", // rgb(50, 205, 50)
    },
    AUTOCAD: {
      name: "Geometria i grafika inżynierska w AUTOCAD",
      teacher: "prof. P. Małka / mgr inż. M. Gibas",
      color: "bg-pink-400", // rgb(255, 105, 180)
    },
    FIZ01: {
      name: "Fizyka",
      teacher: "Pracownicy katedry",
      color: "bg-green-900", // rgb(0, 100, 0)
    },
  },
  SCHEDULE: [
    // PONIEDZIAŁEK (day: 0)
    {
      id: 201,
      subj: "ANAL",
      type: "Wykład",
      groups: [],
      day: 0,
      start: "07:30",
      end: "09:45",
      room: "A2",
      weeks: "both",
    },
    {
      id: 202,
      subj: "ANAL",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 0,
      start: "10:00",
      end: "11:30",
      room: "A2",
      weeks: "both",
    },
    {
      id: 203,
      subj: "ANG01",
      type: "Lektorat",
      groups: ["Lek3"],
      day: 0,
      start: "10:00",
      end: "11:30",
      room: "136SJO",
      weeks: "both",
    },
    {
      id: 204,
      subj: "ANG01",
      type: "Lektorat",
      groups: ["Lek4"],
      day: 0,
      start: "10:00",
      end: "11:30",
      room: "139SJO",
      weeks: "both",
    },
    {
      id: 205,
      subj: "ANAL",
      type: "Ćwiczenia",
      groups: ["Ć2"],
      day: 0,
      start: "11:45",
      end: "13:15",
      room: "A2",
      weeks: "both",
    },
    {
      id: 206,
      subj: "ANG01",
      type: "Lektorat",
      groups: ["Lek1"],
      day: 0,
      start: "11:45",
      end: "13:15",
      room: "139SJO",
      weeks: "both",
    },
    {
      id: 207,
      subj: "ANG01",
      type: "Lektorat",
      groups: ["Lek5"],
      day: 0,
      start: "11:45",
      end: "13:15",
      room: "136SJO",
      weeks: "both",
    },
    {
      id: 208,
      subj: "ANAL",
      type: "Ćwiczenia",
      groups: ["Ć3"],
      day: 0,
      start: "13:30",
      end: "15:00",
      room: "A2",
      weeks: "both",
    },
    {
      id: 209,
      subj: "ANG01",
      type: "Lektorat",
      groups: ["Lek2"],
      day: 0,
      start: "13:30",
      end: "15:00",
      room: "136SJO",
      weeks: "both",
    },
    {
      id: 210,
      subj: "PROG_CPP",
      type: "Projekt",
      groups: ["P1"],
      day: 0,
      start: "13:30",
      end: "15:00",
      room: "19",
      weeks: "even",
    },
    {
      id: 211,
      subj: "PROG_CPP",
      type: "Projekt",
      groups: ["P4"],
      day: 0,
      start: "13:30",
      end: "15:00",
      room: "19",
      weeks: "odd",
    },
    {
      id: 212,
      subj: "ANAL",
      type: "Ćwiczenia",
      groups: ["Ć4"],
      day: 0,
      start: "15:15",
      end: "16:45",
      room: "A2",
      weeks: "both",
    },
    {
      id: 213,
      subj: "PROG_CPP",
      type: "Projekt",
      groups: ["P3"],
      day: 0,
      start: "15:15",
      end: "16:45",
      room: "19",
      weeks: "even",
    },
    {
      id: 214,
      subj: "PROG_CPP",
      type: "Projekt",
      groups: ["P2"],
      day: 0,
      start: "15:15",
      end: "16:45",
      room: "19",
      weeks: "odd",
    },
    {
      id: 215,
      subj: "PROG_CPP",
      type: "Projekt",
      groups: ["P5"],
      day: 0,
      start: "17:00",
      end: "18:30",
      room: "19",
      weeks: "even",
    },

    // WTOREK (day: 1)
    {
      id: 216,
      subj: "ELEC_BAS",
      type: "Wykład",
      groups: [],
      day: 1,
      start: "09:15",
      end: "10:45",
      room: "A4",
      weeks: "both",
    },
    {
      id: 217,
      subj: "NIEM01",
      type: "Lektorat",
      groups: ["Lek"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "139SJO",
      weeks: "both",
    },
    {
      id: 218,
      subj: "ELEC_BAS",
      type: "Ćwiczenia",
      groups: ["Ć2"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "A4",
      weeks: "even",
    },
    {
      id: 219,
      subj: "ELEC_BAS",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 1,
      start: "11:00",
      end: "12:30",
      room: "A4",
      weeks: "odd",
    },
    {
      id: 220,
      subj: "NUMER",
      type: "Wykład",
      groups: [],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "A3",
      weeks: "even",
    },
    {
      id: 221,
      subj: "PROG_CPP",
      type: "Projekt",
      groups: ["P6"],
      day: 1,
      start: "12:45",
      end: "14:15",
      room: "101B",
      weeks: "odd",
    },
    {
      id: 222,
      subj: "AUTOCAD",
      type: "Wykład",
      groups: [],
      day: 1,
      start: "14:30",
      end: "16:00",
      room: "A4",
      weeks: "even",
    },
    {
      id: 223,
      subj: "PROG_CPP",
      type: "Projekt",
      groups: ["P7"],
      day: 1,
      start: "14:30",
      end: "16:00",
      room: "101B",
      weeks: "odd",
    },
    {
      id: 224,
      subj: "AUTOCAD",
      type: "Laboratorium",
      groups: ["Lk6"],
      day: 1,
      start: "16:15",
      end: "17:45",
      room: "13",
      weeks: "both",
    },
    {
      id: 225,
      subj: "PROG_CPP",
      type: "Laboratorium",
      groups: ["Lk7"],
      day: 1,
      start: "16:15",
      end: "17:45",
      room: "19",
      weeks: "both",
    },
    {
      id: 226,
      subj: "AUTOCAD",
      type: "Laboratorium",
      groups: ["Lk7"],
      day: 1,
      start: "18:00",
      end: "19:30",
      room: "13",
      weeks: "both",
    },
    {
      id: 227,
      subj: "PROG_CPP",
      type: "Laboratorium",
      groups: ["Lk6"],
      day: 1,
      start: "18:00",
      end: "19:30",
      room: "19",
      weeks: "both",
    },
    {
      id: 228,
      subj: "AUTOCAD",
      type: "Projekt",
      groups: ["P6"],
      day: 1,
      start: "19:45",
      end: "21:15",
      room: "13",
      weeks: "even",
    },
    {
      id: 229,
      subj: "AUTOCAD",
      type: "Projekt",
      groups: ["P7"],
      day: 1,
      start: "19:45",
      end: "21:15",
      room: "13",
      weeks: "odd",
    },

    // ŚRODA (day: 2)
    {
      id: 230,
      subj: "AUTOCAD",
      type: "Projekt",
      groups: ["P2"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "12",
      weeks: "even",
    },
    {
      id: 231,
      subj: "AUTOCAD",
      type: "Projekt",
      groups: ["P1"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "12",
      weeks: "odd",
    },
    {
      id: 232,
      subj: "NUMER",
      type: "Laboratorium",
      groups: ["Lk1"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "202",
      weeks: "even",
    },
    {
      id: 233,
      subj: "NUMER",
      type: "Laboratorium",
      groups: ["Lk2"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "202",
      weeks: "odd",
    },
    {
      id: 234,
      subj: "ELEC_BAS",
      type: "Ćwiczenia",
      groups: ["Ć3"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "9",
      weeks: "even",
    },
    {
      id: 235,
      subj: "ELEC_BAS",
      type: "Ćwiczenia",
      groups: ["Ć4"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "9",
      weeks: "odd",
    },
    {
      id: 236,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L5"],
      day: 2,
      start: "11:45",
      end: "13:15",
      room: "06",
      weeks: "both",
    },
    {
      id: 237,
      subj: "AUTOCAD",
      type: "Projekt",
      groups: ["P5"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "12",
      weeks: "even",
    },
    {
      id: 238,
      subj: "NUMER",
      type: "Laboratorium",
      groups: ["Lk3"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "202",
      weeks: "even",
    },
    {
      id: 239,
      subj: "NUMER",
      type: "Laboratorium",
      groups: ["Lk5"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "202",
      weeks: "odd",
    },
    {
      id: 240,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L6"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "06",
      weeks: "both",
    },
    {
      id: 241,
      subj: "PROG_CPP",
      type: "Laboratorium",
      groups: ["Lk1"],
      day: 2,
      start: "13:30",
      end: "15:00",
      room: "19",
      weeks: "both",
    },
    {
      id: 242,
      subj: "NUMER",
      type: "Laboratorium",
      groups: ["Lk4"],
      day: 2,
      start: "15:15",
      end: "16:45",
      room: "202",
      weeks: "even",
    },
    {
      id: 243,
      subj: "NUMER",
      type: "Laboratorium",
      groups: ["Lk6"],
      day: 2,
      start: "15:15",
      end: "16:45",
      room: "202",
      weeks: "odd",
    },
    {
      id: 244,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L7"],
      day: 2,
      start: "15:15",
      end: "16:45",
      room: "06",
      weeks: "both",
    },
    {
      id: 245,
      subj: "PROG_CPP",
      type: "Laboratorium",
      groups: ["Lk2"],
      day: 2,
      start: "15:15",
      end: "16:45",
      room: "19",
      weeks: "both",
    },
    {
      id: 246,
      subj: "NUMER",
      type: "Laboratorium",
      groups: ["Lk7"],
      day: 2,
      start: "17:00",
      end: "18:30",
      room: "202",
      weeks: "even",
    },
    {
      id: 247,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L8"],
      day: 2,
      start: "17:00",
      end: "18:30",
      room: "06",
      weeks: "both",
    },
    {
      id: 248,
      subj: "PROG_CPP",
      type: "Laboratorium",
      groups: ["Lk3"],
      day: 2,
      start: "17:00",
      end: "18:30",
      room: "19",
      weeks: "both",
    },
    {
      id: 249,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L11"],
      day: 2,
      start: "18:45",
      end: "20:15",
      room: "06",
      weeks: "both",
    },

    // CZWARTEK (day: 3)
    {
      id: 250,
      subj: "PROG_CPP",
      type: "Wykład",
      groups: [],
      day: 3,
      start: "08:15",
      end: "09:45",
      room: "A3",
      weeks: "both",
    },
    {
      id: 251,
      subj: "AUTOCAD",
      type: "Laboratorium",
      groups: ["Lk1"],
      day: 3,
      start: "10:00",
      end: "11:30",
      room: "13",
      weeks: "both",
    },
    {
      id: 252,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L10"],
      day: 3,
      start: "10:00",
      end: "11:30",
      room: "06",
      weeks: "both",
    },
    {
      id: 253,
      subj: "AUTOCAD",
      type: "Laboratorium",
      groups: ["Lk2"],
      day: 3,
      start: "11:45",
      end: "13:15",
      room: "13",
      weeks: "both",
    },
    {
      id: 254,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L9"],
      day: 3,
      start: "11:45",
      end: "13:15",
      room: "06",
      weeks: "both",
    },
    {
      id: 255,
      subj: "AUTOCAD",
      type: "Laboratorium",
      groups: ["Lk3"],
      day: 3,
      start: "13:30",
      end: "15:00",
      room: "13",
      weeks: "both",
    },
    {
      id: 256,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L1"],
      day: 3,
      start: "13:30",
      end: "15:00",
      room: "06",
      weeks: "both",
    },
    {
      id: 257,
      subj: "AUTOCAD",
      type: "Laboratorium",
      groups: ["Lk4"],
      day: 3,
      start: "15:15",
      end: "16:45",
      room: "13",
      weeks: "both",
    },
    {
      id: 258,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L2"],
      day: 3,
      start: "15:15",
      end: "16:45",
      room: "06",
      weeks: "both",
    },
    {
      id: 259,
      subj: "AUTOCAD",
      type: "Laboratorium",
      groups: ["Lk5"],
      day: 3,
      start: "17:00",
      end: "18:30",
      room: "13",
      weeks: "both",
    },
    {
      id: 260,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L4"],
      day: 3,
      start: "17:00",
      end: "18:30",
      room: "06",
      weeks: "both",
    },
    {
      id: 261,
      subj: "PROG_CPP",
      type: "Laboratorium",
      groups: ["Lk4"],
      day: 3,
      start: "17:00",
      end: "18:30",
      room: "101B",
      weeks: "both",
    },
    {
      id: 262,
      subj: "AUTOCAD",
      type: "Projekt",
      groups: ["P3"],
      day: 3,
      start: "18:45",
      end: "20:15",
      room: "13",
      weeks: "even",
    },
    {
      id: 263,
      subj: "AUTOCAD",
      type: "Projekt",
      groups: ["P4"],
      day: 3,
      start: "18:45",
      end: "20:15",
      room: "13",
      weeks: "odd",
    },
    {
      id: 264,
      subj: "ELEC_BAS",
      type: "Laboratorium",
      groups: ["L3"],
      day: 3,
      start: "18:45",
      end: "20:15",
      room: "06",
      weeks: "both",
    },
    {
      id: 265,
      subj: "PROG_CPP",
      type: "Laboratorium",
      groups: ["Lk5"],
      day: 3,
      start: "18:45",
      end: "20:15",
      room: "101B",
      weeks: "both",
    },

    // PIĄTEK (day: 4)
    {
      id: 266,
      subj: "FIZ01",
      type: "Ćwiczenia",
      groups: ["Ć1"],
      day: 4,
      start: "09:15",
      end: "14:15",
      room: "F",
      weeks: "both",
    },
  ],
};
